# Need to use the net_mgmt network for acces from the Ansible server
#
- name: add facts from OpenStack discovery
  set_fact:
    ansible_ssh_host: "{{ hostvars[inventory_hostname].openstack.addresses.net_mgmt[0].addr }}"

- name: Wait for port 22 to become open
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10 timeout=1200

#- name: Display all variables/facts known for a host
#  debug: var=hostvars[inventory_hostname] verbosity=4
#

# We are going to try to install python 3 times, to avoid network failures
- name: Install python and deps for ansible module 1.try
  raw: sudo dnf install -y python2 python2-dnf
  ignore_errors: yes

- name: Install python and deps for ansible module 2.try
  raw: sudo dnf install -y python2 python2-dnf
  ignore_errors: yes

- name: Install python and deps for ansible module Final Try
  raw: sudo dnf install -y python2 python2-dnf

- name: Make sure libselinux-python are installed
  dnf: name=libselinux-python state=present
  become: yes
  become_user: root

- name: Gather facts
  setup:  

- name: Put a README in place
  copy: src=README dest=/home/opnfv/README

- name: Ensures {{openvpn_dir}} dir exists
  file: path={{openvpn_dir}} state=directory
  become: yes
  become_user: root

- name: Copy test openvpn conf while filling a correct remote server
  template: src=client.conf.j2 dest=/etc/openvpn/client.conf
  become: yes
  become_user: root

- name: Test copy key file
  copy: src=static.key dest=/etc/openvpn/static.key

  become: yes
  become_user: root
- name: Let everyone know we are done
  file: path=/home/opnfv/CONFIGURED state=touch owner=opnfv group=opnfv mode=0775

#- name: Let everyone know we are done
#  template: src=CONFIGURED.j2 dest=/home/opnfv/CONFIGURED owner=opnfv group=opnfv mode="u=rw,g=r,o=r"

- name: start vpn client on host with id==3
  command: sudo systemctl restart openvpn@client.service
  when: ( id == 3 )
