# Need to use the net_mgmt network for acces from the Ansible server
#
#- name: add facts from OpenStack discovery
#  set_fact:
#    ansible_ssh_host: "{{ hostvars[inventory_hostname].openstack.addresses.net_mgmt[0].addr }}"

#- name: Display all variables/facts known for a host
#  debug: var=hostvars[inventory_hostname] verbosity=4
#
- name: Install python and deps for ansible module
  raw: sudo dnf install -y python2 python2-dnf

- name: Make sure libselinux-python are installed
  dnf: name=libselinux-python state=present
  become: yes
  become_user: root

- name: Gather facts
  setup:  

- name: Put a README in place
  copy: src=README dest=/home/opnfv/README

- name: Ensures {{openvpn_dir}} dir exists
  file: path={{openvpn_dir}} state=directory

- name: Copy test openvpn conf
  copy: src=server.conf dest=/home/opnfv/openvpn/client.conf

- name: Test copy key file
  copy: src=static.key dest=/home/opnfv/openvpn/static.key

- name: Let everyone know we are done
  file: path=/home/opnfv/CONFIGURED state=touch owner=opnfv group=opnfv mode=0775

#- name: Let everyone know we are done
#  template: src=CONFIGURED.j2 dest=/home/opnfv/CONFIGURED owner=opnfv group=opnfv mode="u=rw,g=r,o=r"

